-- ==========================================================
-- Exam Preparation Planner - Database Creation Script
-- Run with: sqlite3 planner.db < schema.sql
-- (Note: the app itself creates these automatically via database.py,
--  this file is provided separately as required project documentation)
-- ==========================================================

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
    user_id     INTEGER PRIMARY KEY AUTOINCREMENT,
    username    TEXT NOT NULL UNIQUE,
    password    TEXT NOT NULL,
    full_name   TEXT NOT NULL,
    created_on  TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS subjects (
    subject_id    INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id       INTEGER NOT NULL,
    subject_name  TEXT NOT NULL,
    total_topics  INTEGER NOT NULL DEFAULT 0,
    created_on    TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    UNIQUE(user_id, subject_name)
);

CREATE TABLE IF NOT EXISTS exams (
    exam_id     INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id     INTEGER NOT NULL,
    subject_id  INTEGER NOT NULL,
    exam_name   TEXT NOT NULL,
    exam_date   TEXT NOT NULL,
    exam_time   TEXT,
    venue       TEXT,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subjects(subject_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS study_plans (
    plan_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id       INTEGER NOT NULL,
    subject_id    INTEGER NOT NULL,
    topic_name    TEXT NOT NULL,
    plan_type     TEXT NOT NULL CHECK(plan_type IN ('Daily','Weekly','Monthly')),
    plan_date     TEXT NOT NULL,
    study_hours   REAL NOT NULL DEFAULT 0,
    is_completed  INTEGER NOT NULL DEFAULT 0 CHECK(is_completed IN (0,1)),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subjects(subject_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS progress (
    progress_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id            INTEGER NOT NULL,
    subject_id         INTEGER NOT NULL,
    completed_topics   INTEGER NOT NULL DEFAULT 0,
    total_topics       INTEGER NOT NULL DEFAULT 0,
    last_updated       TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subjects(subject_id) ON DELETE CASCADE,
    UNIQUE(subject_id)
);

-- Sample demo user (username: student, password hash for 'student123')
-- Password hashing is SHA-256, generated by the app itself on first run.
